apiVersion: v1
kind: Service
metadata:
  name: todolist-app-service
spec:
  type: LoadBalancer
  selector:
    app: todolist-app
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 80  
